spring:
  jpa:
    show-sql: true
  sys:
    datasource:
      url: jdbc:mysql://localhost:3306/mysql
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
  custom:
    datasource:
      url: jdbc:mysql://localhost:3306/emp
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
ttttt:
  ddddd: prod
logging:
  file: D:/logs/prod.log
  pattern:
    console:  "%d %-5level [%thread] %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
#    org.springframework.web: DEBUG
#    org.springframework.jdbc: DEBUG
    org.springframework.transaction: TRACE


    com.data.datachange: DEBUG