spring:
  profiles:
    active: dev
  redis:
    database: 1
    host: localhost
    port: 6379
    password: 11223344
    timeout: 0
    jedis:
      pool:
        max-active: 8
        max-idle: 8
  # 集成 ActiveMQ
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    pool:
      enabled: true
      max-connections: 50
      expiry-timeout: 10
      idle-timeout: 30

