spring:
  sys:
    datasource:
      url: jdbc:mysql://localhost:3306/sys
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
  custom:
    datasource:
      url: jdbc:mysql://localhost:3306/mysql
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
